mentorpal/mentor-admin

- client/src/components/home/index.tsx
- client/src/components/login.tsx
- client/src/components/nav-bar.tsx
- client/src/pages/author/questions.tsx
- client/src/pages/author/subject.tsx
- client/src/pages/author/subjects.tsx
- client/src/pages/feedback.tsx
- client/src/pages/profile.tsx
- client/src/pages/record.tsx
- client/src/pages/setup.tsx
- client/src/pages/subjects.tsx
- cypress/cypress/integration/login.spec.ts
Fix: remove setCookie from nav-menu
> Fix: nav-bar doesn't fetch mentor, only receives the id

- client/src/components/home/index.tsx
- client/src/components/login.tsx
- client/src/components/setup-slides.tsx
- cypress/cypress/integration/setup.spec.ts
Fixed: home screen shouldn't end training unless status is SUCCESS or FAILED
Fixed: setup tests shouldn't need requiredSubjects anymore
Fixed: setup training should update mentor when status is NOT pending
> Local storage fixes

- client/.eslintignore
- client/gatsby-browser.js
- client/package-lock.json
- client/package.json
- client/src/api.ts
- client/src/components/author/question-topics-list.tsx
- client/src/components/home/index.tsx
- client/src/components/record/video-player.jsx
- client/src/components/setup-slides.tsx
- client/src/pages/feedback.tsx
- client/src/pages/record.tsx
- client/src/react-video-recorder.d.ts
- client/src/types.ts
- client/src/use-interval.tsx
- cypress/cypress/integration/author-subject.spec.ts
- cypress/cypress/integration/home.spec.ts
- cypress/cypress/integration/record.spec.ts
- cypress/cypress/integration/setup.spec.ts
- cypress/cypress/support/functions.ts
- cypress/cypress/support/types.ts
- fix: home screen wasn't actually waiting for training to complete
WIP:
- add types and api call for uploadVideo and VideoUploadState
- record screen calls uploadVideo and waits for upload+transcribe
> Video Recorder stuff

- .github/workflows/test-and-publish.yml
- client/package-lock.json
- client/package.json
Run audit fix in client (still some errors)
> Remove gha audit test

- client/src/components/home/index.tsx
- client/src/components/stage-card.tsx
- client/src/components/stage-toast.tsx
- cypress/cypress/integration/home.spec.ts
Shows mentor scope card in question review. Stages encourage users to improve their mentors.
> 4.1.x - user sees the 'scope' of their virtual mentor to encourage making a better mentor

- Makefile
- client/Makefile
Currently, there's "make format". We should have a new rule "make pretty".
Basically, "make format" will do pretty and license.
> fixed makefile

- README.md
Instructions for windows 10 dev added to README and ready to review.
> Instructions for windows 10 dev added

- client/src/components/nav-bar.tsx
- client/src/components/progress-bar.tsx
- client/src/hooks/graphql/use-with-review-answer-state.tsx
- cypress/cypress/integration/home.spec.ts
Home (My Mentor) page now shows all categories when selecting all subjects.
Category progress is now filled radio buttons instead of linear progress bar.
Changed page title in Nav Bar.
> 4.2.x - UI changes to My Mentor Page

- client/src/components/home/recording-block.tsx
- client/src/components/my-mentor-card/index.tsx
- client/src/components/my-mentor-card/recommended-action-button.tsx
- client/src/components/my-mentor-card/use-with-recommended-action.tsx
- client/src/components/progress-bar.tsx
- client/src/components/progress-checks.tsx
- cypress/cypress/fixtures/mentor/clint_home.ts
- cypress/cypress/integration/mentor-card.spec.ts
fixed thumbnail check, name and title separated
> Recommendation button polish

- client/src/pages/profile.tsx
small last change then we should be good to go
> fix: no optional-chain operator on a type that has been narrowed

- client/src/components/home/index.tsx
- client/src/hooks/graphql/use-with-setup.tsx
- client/src/store/slices/mentor/index.ts
- cypress/cypress/integration/home.spec.ts
- cypress/cypress/integration/index.spec.ts
- cypress/cypress/integration/mentor-card.spec.ts
- cypress/cypress/integration/setup.spec.ts
- if no mentor info, redirect
- otherwise, offer to redirect and go to step that needs completing
> If setup is not complete, redirect to setup page from home page:

- client/gatsby-config.js
- client/package-lock.json
- client/package.json
> docker build works on m1 mac machines

- client/src/components/my-mentor-card/use-with-recommended-action.tsx
> Recommended "Build" doesn't work in My Mentor

- client/src/api.ts
- client/src/hooks/graphql/use-with-followups.tsx
- cypress/cypress/support/functions.ts
- Admin hits updated classifier followup entry point.
> new followups endpoint format

- README.md
npm cy:open doesn't work, and it should be npm run cy:open instead
> Fixed the final bullet point for Windows 10 Dev

- client/package-lock.json
- client/package.json
- client/src/components/record/video-player.tsx
- client/src/hooks/graphql/use-with-review-answer-state.tsx
1. Only questions with valid object id's are requested for reload
> Sentry bug fixes

- client/src/components/setup/select-keywords-slide.tsx
- cypress/cypress/integration/setup.spec.ts
keyword buttons in lowercase, remove setup keyword slide directions
> Small cleanup

- client/package.json
- client/src/api.ts
- client/src/components/column-header.tsx
- client/src/hooks/graphql/use-with-data-connection.ts
- client/src/hooks/graphql/use-with-static-data-connection.ts
- client/src/hooks/graphql/use-with-users.tsx
- client/src/pages/users.tsx
- cypress/cypress/fixtures/users.ts
- cypress/cypress/integration/users.spec.ts
Users page uses client-side pagination, search, and filter
> Can search users by user name

- Makefile
- client/src/api.ts
- client/src/hooks/graphql/use-with-config.tsx
- client/src/pages/config.tsx
- client/src/types.ts
- cypress/cypress/integration/config.spec.ts
- cypress/cypress/support/functions.ts
Can organize active mentor panels in config page
> Add active mentor panels to config

- client/src/hooks/graphql/use-with-config.tsx
Fix random ordering of mentorpanels on config page
> Fix random ordering of mentors on config page

- client/src/components/config/color-picker.tsx
- client/src/components/config/home-styles.tsx
- client/src/components/config/image-tutorials.tsx
- client/src/components/config/mentor-list.tsx
- client/src/components/config/mentor-panel-list.tsx
- client/src/components/config/other-settings.tsx
- client/src/components/config/prompts.tsx
- client/src/helpers.ts
- client/src/hooks/graphql/use-with-config.tsx
- client/src/hooks/graphql/use-with-setup.tsx
- client/src/pages/config.tsx
- client/src/pages/organizations.tsx
Add footer images to config
Cleanup config color pickers and help guide
> Fix: using nav bar to leave setup privacy page saves settings

- client/src/api.ts
- client/src/components/config/home-styles.tsx
- client/src/components/setup/mentor-privacy-slide.tsx
- client/src/helpers.ts
- client/src/pages/config.tsx
- client/src/pages/users.tsx
- client/src/types.ts
Mentor org permissions are separated into view and edit
> Upload header and footer images for orgs

- client/src/api.ts
- client/src/components/column-header.tsx
- client/src/components/config/mentor-panel-list.tsx
- client/src/components/config/prompts.tsx
- client/src/components/setup/mentor-privacy-slide.tsx
- client/src/hooks/graphql/use-with-config.tsx
- client/src/hooks/graphql/use-with-static-data-connection.ts
- client/src/hooks/graphql/use-with-users.tsx
- client/src/pages/config.tsx
- client/src/pages/users.tsx
- client/src/types.ts
- cypress/cypress/integration/home.spec.ts
- cypress/cypress/integration/setup.spec.ts
Can archive mentors from users page
Change mentor org privacy text
> Can delete mentor panels

- client/src/api.ts
- client/src/components/login.tsx
- client/src/components/record/video-player.tsx
- client/src/hooks/graphql/use-with-record-state.tsx
- client/src/hooks/graphql/use-with-users.tsx
- client/src/hooks/wrap-with-authorization-only.jsx
- client/src/pages/record.tsx
- client/src/pages/users.tsx
- client/src/store/slices/login/index.ts
- client/src/types-gql.ts
- client/src/types.ts
- cypress/cypress.json
- cypress/cypress/integration/organization.spec.ts
Disabled users cannot login to system and see a different page
Can set mentors to advanced
Advanced mentors can manually set URLs for videos
> Can disable users

- client/src/hooks/graphql/use-with-upload-status.tsx
- client/src/store/slices/mentor/index.ts
> fix QA bugs
